Network:
 host: 127.0.0.1
 port: 3333
 timeout: 300
cluster_35_PFMC:
 OCC_theshold:
  A: [1.5, 2]
  B: [2, 2.3]
  C: [2.3, 2.6]
  F: [2.6, 1.5]

 Buccal_theshold:
  A: [1.2, 1.5]
  B: [1.5, 1.725]
  C: [1.725, 1.95]
  F: [1.95, 1.2]
  
 Lingual_theshold:
  A: [1.2, 1.5]
  B: [1.5, 1.725]
  C: [1.725, 1.95]
  F: [1.95, 1.2]
  
 Proximal_theshold:
  A: [1.2, 1.5]
  B: [1.5, 1.725]
  C: [1.725, 1.95]
  F: [1.95, 1.2]
  
 FinishingLineB_theshold:
  A: [1.2, 1.5]
  B: [1.5, 1.725]
  C: [1.725, 1.95]
  F: [1.95, 1.2]
    
 FinishingLineL-Distal_theshold:
  A: [0.6, 1]
  B: [1, 1.15]
  C: [1.15, 1.3]
  F: [1.3, 0.6]
  
 TOC_theshold:
  A: [0.0, 10]
  B: [10, 15]
  C: [15, 20]
  F: [0.0,20]
 Final_score:
   A: [300,360]
   B : [240,300]
   C: [216,240]
   F : [216]

 Header_Format:
   - "student_id"
   - "name"
   - "Final_grade"
   - "Total_score"
   - "Overall_grade"
   - "OCC_score"
   - "OCC_central-groove_grade"
   - "OCC_B-func_grade"
   - "OCC_L-incline of B cusp_grade"
   - "OCC_L nonfunc_grade"
   - "OCC_B incline of L cusp_grade"
   - "Buccal_score"
   - "Buccal_B plane1_grade"
   - "Buccal_B plane2_grade"
   - "Lingual_score"
   - "Lingual_plane1_grade"
   - "Lingual_plane2_grade"
   - "Proximal_score"
   - "Proximal_Mesial_grade"
   - "Proximal_Distal_grade"
   - "FinishingLine_score"
   - "FinishingLine_Buccal_grade"
   - "FinishingLine_Lingual_grade"
   - "FinishingLine_Mesial_grade"
   - "FinishingLine_Distal_grade"
   - "TOC_score"
   - "TOC_BL_grade"
   - "TOC_MD_grade"
   - "issue"

cluster_11_lithium:
   incisal_edge :
    A : [1.5,2]
    B : [2, 2.3]
    C :  [2.3,2.6]
   
   Buccal:
    A: [1,1.5]
    B: [1.5,1.725]
    C: [1.725,1.95]
   
   Lingual:
    A : [1,1.5]
    B : [1.5,1.725]
    C : [1.725, 1.95]
   
   Proximal:
    A: [1.1,1.5]
    B: [1.5,1.725]
    C: [1.725,1.95]

   Finishing_line :
    A: [0.5,1]
    B: [1,1.15]
    C: [1.15, 1.3]

   TOC:
    A : [0,10]
    B: [10,15]
    C: [15,20]
   
   Final_score:
    A: [300,360]
    B : [240,300]
    C: [216,240]
    F : [216]
   
   Header_Format:
   - "student_id"
   - "name"
   - "total_score"
   - "final_grade"
   - "overall_grade"
   - "incisal_score"
   - "incisal_grade"
   - "buccal_score"
   - "buccal_BP1_grade"
   - "buccal_BP2_grade"
   - "ligual_score"
   - "ligual_LP1_grade"
   - "ligual_LP2_grade"
   - "proximal_score"
   - "proximal_mesial_garde"
   - "proximal_distal_garde"
   - "finishing_line_score"
   - "finishing_line_B_garde"
   - "finishing_line_L_garde"
   - "finishing_line_mesial_garde"
   - "finishing_line_distal_garde"
   - "toc_score"
   - "toc_bl_grade"
   - "toc_md_grade"
   - "issue"
   
cluster_16_PFMC:
   occ_16PFMC:
      A: [1.5,2]
      B: [2,2.3]
      C: [2.3,2.6]

   buccal_16PFMC:
      A: [1.2,1.5]
      B: [1.5,1.725]
      C: [1.725,1.95]

   lingual_16PFMC:
      A: [1,1.5]
      B: [1.5,1.725]
      C: [1.725, 1.95]

   proximal_16PFMC:
      A: [1,1.5]
      B: [1.5, 1.725]
      C: [1.725, 1.95]

   finishing_line_MDandDB:
      A: [1.2,1.5]
      B: [1.5,1.725]
      C: [1.725, 1.95]

   finishing_line_ML-DL:
      A: [0.6,1]
      B: [1,1.15]
      C: [1.15, 1.3]

   toc_16PFMC:
      A: [0,10]
      B: [10,15]
      C: [15,20]
   Final_score:
    A: [300,360]
    B : [240,300]
    C: [216,240]
    F : [216]
   Header_Format:
   - "student_id"
   - "name"
   - "total_score"
   - "final_grade"
   - "overall_grade"
   - "OCC_score"
   - "OCC_MB_cusp_grade"
   - "OCC_MB_incline_grade"
   - "OCC_MB_groove_grade"
   - "OCC_DB_cusp_grade"
   - "OCC_DB_incline_grade"
   - "OCC_DB_groove_grade"
   - "OCC_ML_cusp_grade"
   - "OCC_ML_incline_grade"
   - "OCC_ML_groove_grade"
   - "OCC_DL_cusp_grade"
   - "OCC_DL_incline_grade"
   - "OCC_DL_groove_grade"
   - "Buccal_score"
   - "Buccal_MBP1_grade"
   - "Buccal_MBP2_grade"
   - "Buccal_DBP1_grade"
   - "Buccal_DBP2_grade"
   - "Lingual_score"
   - "Lingual_MLP1_grade"
   - "Lingual_MLP2_grade"
   - "Lingual_DLP1_grade"
   - "Lingual_DLP2_grade"
   - "Proximal_score"
   - "Proximal_mesial_grade"
   - "Proximal_distal_grade"
   - "Finishing_line_score"
   - "Finishing_line_MB_grade"
   - "Finishing_line_ML_grade"
   - "Finishing_line_DB_grade"
   - "Finishing_line_DL_grade"
   - "Finishing_line_mesial_grade"
   - "Finishing_line_distal_grade"
   - "TOC_score"
   - "TOC_MD_grade"
   - "TOC_BL_grade"
   - "issue"

cluster_46_FMC:
   occ_46FMC1:
      A: [1.5,2]
      B: [2,2.3]
      C: [2.3,2.6]
   occ_46FMC2:
      A: [1,1.5]
      B: [1.5,1.725]
      C: [1.725,1.95]

   buccal_46FMC:
      A: [1,1.5]
      B: [1.5,1.725]
      C: [1.725,1.95]

   lingual_46FMC:
      A: [1,1.5]
      B: [1.5,1.725]
      C: [1.725, 1.95]

   proximal_46FMC:
      A: [1.2,1.5]
      B: [1.5, 1.725]
      C: [1.725, 1.95]

   finishing_line:
      A: [0.5,0.8]
      B: [0.8,0.92]
      C: [0.92, 1.04]

   toc_46FMC:
      A: [0,10]
      B: [10,15]
      C: [15,20]
   Final_score:
    A: [300,360]
    B : [240,300]
    C: [216,240]
    F : [216]
   Header_Format:
   - "student_id"
   - "name"
   - "total_score"
   - "final_grade"
   - "overall_grade"
   - "OCC_score"
   - "OCC_MB_cusp_grade"
   - "OCC_MB_incline_grade"
   - "OCC_MB_groove_grade"
   - "OCC_DB_cusp_grade"
   - "OCC_DB_incline_grade"
   - "OCC_DB_groove_grade"
   - "OCC_ML_cusp_grade"
   - "OCC_ML_incline_grade"
   - "OCC_ML_groove_grade"
   - "OCC_DL_cusp_grade"
   - "OCC_DL_incline_grade"
   - "OCC_DL_groove_grade"
   - "Buccal_score"
   - "Buccal_MBP1_grade"
   - "Buccal_MBP2_grade"
   - "Buccal_DBP1_grade"
   - "Buccal_DBP2_grade"
   - "Lingual_score"
   - "Lingual_MLP1_grade"
   - "Lingual_MLP2_grade"
   - "Lingual_DLP1_grade"
   - "Lingual_DLP2_grade"
   - "Proximal_score"
   - "Proximal_mesial_grade"
   - "Proximal_distal_grade"
   - "Finishing_line_score"
   - "Finishing_line_MB_grade"
   - "Finishing_line_ML_grade"
   - "Finishing_line_DB_grade"
   - "Finishing_line_DL_grade"
   - "Finishing_line_mesial_grade"
   - "Finishing_line_distal_grade"
   - "TOC_score"
   - "TOC_MD_grade"
   - "TOC_BL_grade"
   - "issue"

cluster_37_FMC:
   occ_37FMC1:
      A: [1.5,2]
      B: [2,2.3]
      C: [2.3,2.6]
   occ_37FMC2:
      A: [1,1.5]
      B: [1.5,1.725]
      C: [1.725,1.95]

   buccal_37FMC:
      A: [1,1.5]
      B: [1.5,1.725]
      C: [1.725,1.95]

   lingual_37FMC:
      A: [1,1.5]
      B: [1.5,1.725]
      C: [1.725, 1.95]

   proximal_37FMC:
      A: [1.2,1.5]
      B: [1.5, 1.725]
      C: [1.725, 1.95]

   finishing_line:
      A: [0.5,0.8]
      B: [0.8,0.92]
      C: [0.92, 1.04]

   toc_37FMC:
      A: [0,10]
      B: [10,15]
      C: [15,20]
   Final_score:
    A: [300,360]
    B : [240,300]
    C: [216,240]
    F : [216]
   Header_Format:
   - "student_id"
   - "name"
   - "total_score"
   - "final_grade"
   - "overall_grade"
   - "OCC_score"
   - "OCC_MB_cusp_grade"
   - "OCC_MB_incline_grade"
   - "OCC_MB_groove_grade"
   - "OCC_DB_cusp_grade"
   - "OCC_DB_incline_grade"
   - "OCC_DB_groove_grade"
   - "OCC_ML_cusp_grade"
   - "OCC_ML_incline_grade"
   - "OCC_ML_groove_grade"
   - "OCC_DL_cusp_grade"
   - "OCC_DL_incline_grade"
   - "OCC_DL_groove_grade"
   - "Buccal_score"
   - "Buccal_MBP1_grade"
   - "Buccal_MBP2_grade"
   - "Buccal_DBP1_grade"
   - "Buccal_DBP2_grade"
   - "Lingual_score"
   - "Lingual_MLP1_grade"
   - "Lingual_MLP2_grade"
   - "Lingual_DLP1_grade"
   - "Lingual_DLP2_grade"
   - "Proximal_score"
   - "Proximal_mesial_grade"
   - "Proximal_distal_grade"
   - "Finishing_line_score"
   - "Finishing_line_MB_grade"
   - "Finishing_line_ML_grade"
   - "Finishing_line_DB_grade"
   - "Finishing_line_DL_grade"
   - "Finishing_line_mesial_grade"
   - "Finishing_line_distal_grade"
   - "TOC_score"
   - "TOC_MD_grade"
   - "TOC_BL_grade"
   - "issue"

Encrypt:
   secret: c5b91e484e3b3efa6f769b39a3bb2cc3
   